// Loading favourites
export const REQUEST_ACTIVITIES = 'REQUEST_ACTIVITIES';
export const ACTIVITIES_SUCCESS = 'ACTIVITIES_SUCCESS';
export const ACTIVITIES_FAILURE = 'ACTIVITIES_FAILURE';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const DECREMENT_PAGE = 'DECREMENT_PAGE';
export const FIRST_PAGE = 'FIRST_PAGE';
export const LAST_PAGE = 'LAST_PAGE';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const ADD_NEW_ACTIVITY = 'ADD_NEW_ACTIVITY';