// Loading image
export const REQUEST_VOTING_IMAGE = 'REQUEST_VOTING_IMAGE';
export const VOTING_IMAGE_FAILURE = 'VOTING_IMAGE_FAILURE';
export const VOTING_IMAGE_SUCCESS = 'VOTING_IMAGE_SUCCESS';

// Voting image
export const REQUEST_VOTE_IMAGE = 'REQUEST_VOTE_IMAGE';
export const VOTE_IMAGE_SUCCESS = 'VOTE_IMAGE_SUCCESS';
export const VOTE_IMAGE_FAILURE = 'VOTE_IMAGE_FAILURE';

// Saving image
export const REQUEST_SAVE_IMAGE = 'REQUEST_SAVE_IMAGE';
export const SAVE_IMAGE_SUCCESS = 'SAVE_IMAGE_SUCCESS';
export const SAVE_IMAGE_FAILURE = 'SAVE_IMAGE_FAILURE';